### ISSUE TITLE
Mac arm版需求

### ISSUE THREAD

**Issue by t1gress** [yhy0/Jie#11]
师傅，什么时候能推出支持arm架构的包呀

**Comment by yhy0** [comment]
快了，计划 2024 年 1 月 1 号更新到最新版，大量重构，新增了被动扫描，更好的辅助挖洞，不太一样的体验(自我感觉[旺柴])。
目前基本重构完成，就剩下测试了，这个月有时间会测试，没时间测试也会放出来 🐶
