### ISSUE TITLE
请问只进行指纹扫描

### ISSUE THREAD

**Issue by zglaozhu** [yhy0/Jie#13]
请问只进行指纹扫描，不进行漏洞扫描的话，被动扫描参数怎么设置？

**Comment by yhy0** [comment]
1. 启动时指定 --np 禁用所有扫描插件
2. 修改 `Jie_config.yaml` 中的所有插件开关为 false
3. 通过 web 的配置页面关闭所有插件

**Comment by zglaozhu** [comment]
> 1. 启动时指定 --np 禁用所有扫描插件
> 2. 修改 `Jie_config.yaml` 中的所有插件开关为 false
> 3. 通过 web 的配置页面关闭所有插件

谢谢，请问什么参数可以指定扫描速度呢？

**Comment by yhy0** [comment]
配置文件中的 parallel 和 maxQps 参数，更加细化的没写。建议看看配置文件，都有注释

**Comment by zglaozhu** [comment]
> 配置文件中的 parallel 和 maxQps 参数，更加细化的没写。建议看看配置文件，都有注释

好的，谢谢啦 我去试试
