### ISSUE TITLE
请问默认口令是？

### ISSUE THREAD

**Issue by zglaozhu** [yhy0/Jie#14]
http://127.0.0.1:9088/

yhy
123456
我用上面的访问失败
![image](https://github.com/yhy0/Jie/assets/31888299/cf8278e3-4f30-4374-b901-321ff4a790b3)

**Comment by yhy0** [comment]
没有默认口令，不指定会自动生成一个密码，日志中搜索一下 `Security Copilot web report authorized`

**Comment by zglaozhu** [comment]
谢谢，我知道了 --user yhy --pwd 123
