### ISSUE TITLE
请问在命令行怎么启用所有扫描插件？

### ISSUE THREAD

**Issue by zglaozhu** [yhy0/Jie#15]
Jie web -t https://public-firing-range.appspot.com/ -p all -o vulnerability_report.html --copilot ?
是这样吗？

**Comment by yhy0** [comment]
没写全部开启的，你可以在配置文件中全部打开，这样之后就不用指定了

**Comment by yhy0** [comment]
已更新，可以下载代码自行编译尝试，指定 -p all 开启全部插件

**Comment by zglaozhu** [comment]
> 已更新，可以下载代码自行编译尝试，指定 -p all 开启全部插件

ok
