### ISSUE TITLE
web 的配置界面无法保存更改的功能

### ISSUE THREAD

**Issue by epony4c** [yhy0/Jie#16]
![image](https://github.com/yhy0/Jie/assets/17228839/7dd180b4-1574-4614-8dbe-1b91fe104b4e)

无法更新配置；

**Comment by yhy0** [comment]
已修复，但目前还有个问题，就是 web 页面修改并不能同步修改配置文件，主要是使用 viper 写入更改会导致注释消失，等我想想怎么解决。
如果在通过 web修改后，又修改配置文件后，这时配置是通过配置文件获取的，会覆盖之前通过 web 修改的，所以要注意 web 和配置文件的差异
