### ISSUE TITLE
Ubuntu 运行报错问题

### ISSUE THREAD

**Issue by MaxSecurity** [yhy0/Jie#18]
/Jie 
./Jie: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Jie)
./Jie: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Jie)

运行报错

**Comment by yhy0** [comment]
因为端口扫描使用的 naabu ，这个需要机器安装 libpcap

**Comment by MaxSecurity** [comment]
> 因为端口扫描使用的 naabu ，这个需要机器安装 libpcap

OK我这边尝试一下

**Comment by MaxSecurity** [comment]
> 因为端口扫描使用的 naabu ，这个需要机器安装 libpcap

已经安装完整了 还是不行

**Comment by yhy0** [comment]
https://blog.csdn.net/huazhang_001/article/details/128828999 这个有尝试吗？或者你自己在你的Ubuntu机器上编译文件，而不是下载 release 的

**Comment by MaxSecurity** [comment]
> https://blog.csdn.net/huazhang_001/article/details/128828999 这个有尝试吗？或者你自己在你的Ubuntu机器上编译文件，而不是下载 release 的

这个解决还是不行 直接用go编译也是失败的难绷

**Comment by yhy0** [comment]
这个是因为 release 中是使用 ubuntu-22.04 编译的，低版本的 glibc 会出现这个问题，目前的解决方案是
- 升级glibc版本或者升级系统
- 将项目 clone 到机器上，然后执行 make 构建 
不清楚你使用 go 变异报的是什么错

**Comment by yhy0** [comment]
已去除 naabu 依赖，改用 masscan 和 nmap
