### ISSUE TITLE
老哥，你xss的js语义分析的地方有点问题

### ISSUE THREAD

**Issue by sairson** [yhy0/Jie#2]
![image](https://user-images.githubusercontent.com/74412075/233786255-52bef9f7-dece-4fbb-a952-7de34407362b.png)
这点你是不是还没写完😂，glint项目中的html语法树有点问题（我已经给提issues了），多层的节点，它解析不出来，其次glint中的语法树部分不会生成BlockComment这些，w13scan和glint结合的话需要对这一部分改改

**Comment by yhy0** [comment]
感谢，我瞅瞅看看怎么写，刚学

**Comment by sairson** [comment]
glint中的Byte2Str存在内存覆盖问题，在解析html语法树的时候，建议使用string函数，虽然效率会慢，但是不会出现转换问题，可以注意一下

**Comment by yhy0** [comment]
感谢，大佬太强了
