### ISSUE TITLE
所以这个证书应该怎么安装，看了半天没看懂，可以在源项目里带一个证书嘛？剑仙

### ISSUE THREAD

**Issue by ss3931** [yhy0/Jie#22]
所以这个证书应该怎么安装，看了半天没看懂，可以在源项目里带一个证书嘛？剑仙

**Comment by ss3931** [comment]
> 证书会在首次启动命令后自动生成，路径为 ~/.mitmproxy/mitmproxy-ca-cert.pem。
> 
> 安装信任根证书, 安装步骤可参考 Python mitmproxy 文档：[About Certificates](https://docs.mitmproxy.org/stable/concepts-certificates/)。

是不是就是 把mitmproxy-ca-cert.cer  装到受信任的根节点 就行了

**Comment by yhy0** [comment]
是的
