### ISSUE TITLE
剑仙，为什么我跑每一个站点，都会有这个报错。  ERROR [waybackarchive:waybackarchive.go(Run):24] WayBackArchive err: Get "http://web.archive.org/cdx/search/cdx?url=http://39.xxx.xxx.xxx:1901/*&output=txt&fl=original&collapse=urlkey&fastLatest=true": context deadline exceeded

### ISSUE THREAD

**Issue by ss3931** [yhy0/Jie#23]
ERROR [waybackarchive:waybackarchive.go(Run):24] WayBackArchive err: Get "http://web.archive.org/cdx/search/cdx?url=http://39.xxx.xxx.xxx:1901/*&output=txt&fl=original&collapse=urlkey&fastLatest=true": context deadline exceeded

**Comment by yhy0** [comment]
这是尝试从http://web.archive.org/ 这个网站获取你扫描站点的历史url，这里报错应该是请求过多导致的，我后面看看这一块怎么优化，或者效果不好的话我去除掉
这个报错不影响使用
