### ISSUE TITLE
Error executing template: template: vuln_report:54:80: executing "vuln_report" at <.VulnData.Plugin>: can't evaluate field Plugin in type output.VulnData

### ISSUE THREAD

**Issue by zdone** [yhy0/Jie#24]
你好；这个软件看着就很棒~~但是目前在测试的时候，报错了。

报错内容：
ERROR [output:report.go(GenerateVulnReport):48] Error executing template: template: vuln_report:54:80: executing "vuln_report" at <.VulnData.Plugin>: can't evaluate field Plugin in type output.VulnData

测试命令如下：
./Jie web -t   http://testphp.vulnweb.com/ -p all -o 1.html --copilot

系统win11；
软件版本：最新版1.0.6

**Comment by yhy0** [comment]
已修复
