### ISSUE TITLE
被动扫描模式下：有时候浏览很多页面后，不就不会进行任务探测了。会卡住

### ISSUE THREAD

**Issue by zdone** [yhy0/Jie#27]
hi~亲爱的大大，
被动扫描模式下：有时候浏览很多页面后，不就不会进行任务探测了。代码一直循环在Progress()函数内。
在命令行一直显示：
A total of 85 tasks have been received, 0 have been processed, and the processing rate is 0.00%

稍微调试f8跟了一下，在task\task.go下，
func (t *Task) Distribution(in *input.CrawlResult) {
    if !conf.NoProgressBar {
        atomic.AddInt64(&output.TaskCounter, 1)
    }
    
    t.Wg.Add()  //  运行到这里，后面的代码都运行不到了。。。

也不知道为什么；

**Comment by yhy0** [comment]
1.0.8 版本 还是，自己拉取的最新代码构建的？如果是 1.0.8 的话可以尝试拉取最新代码构建 然后再跑一下试试，最新的提交了这个commit  https://github.com/yhy0/Jie/commit/3fc391e0d6aea3cdcf9c8950f08209b6f07b2adb 
如果还有问题，我抽时间看看

**Comment by zdone** [comment]
拉取的最新的。banner 写着： 1.10 ，长时间跑一下，比如超过5~10分钟。测试的网站：http://testphp.vulnweb.com/，然后再换新网站。然后所有探测任务都失败了。

**Comment by zdone** [comment]
> 1.0.8 版本 还是，自己拉取的最新代码构建的？如果是 1.0.8 的话可以尝试拉取最新代码构建 然后再跑一下试试，最新的提交了这个commit [3fc391e](https://github.com/yhy0/Jie/commit/3fc391e0d6aea3cdcf9c8950f08209b6f07b2adb) 如果还有问题，我抽时间看看

拉取的最新的。banner 写着： 1.10 ，长时间跑一下，比如超过5~10分钟。测试的网站：[http://testphp.vulnweb.com/，然后再换新网站。然后所有探测任务都失败了。
谢谢大大

**Comment by yhy0** [comment]
ok, 这周我有时间的话看看

**Comment by anasbousselham** [comment]
我有同样的问题，什么都不起作用，也没有检测到，就停在这里：A total of 59 tasks have been received, 1 have been processed, and the processing rate is 1.69%

**Comment by Miracles666** [comment]
同上

**Comment by khanjanny** [comment]
Same as above, task stuck...

**Comment by yhy0** [comment]
已修复
