### ISSUE TITLE
mac编译问题

### ISSUE THREAD

**Issue by lemonlove7** [yhy0/Jie#3]
(base) lemonlove7@xiaobaideAir Jie-main % CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build
package github.com/yhy0/Jie
	imports github.com/yhy0/Jie/cmd
	imports github.com/yhy0/Jie/pkg/task
	imports github.com/yhy0/Jie/scan/bbscan
	imports github.com/yhy0/Jie/scan/brute
	imports github.com/yhy0/Jie/scan/brute/hydra
	imports github.com/tomatome/grdp/protocol/pdu
	imports github.com/tomatome/grdp/protocol/t125/gcc
	imports github.com/tomatome/grdp/plugin: build constraints exclude all Go files in /Users/lemonlove7/go/pkg/mod/github.com/tomatome/grdp@v0.1.0/plugin
报错这个

**Comment by yhy0** [comment]
应该是 CGO_ENABLED=0 这个参数问题，我记得弱口令爆破中有个包不能禁用CGO，你可以把 `brute/hrdra` 整个都删掉，没有用到，或者不禁用CGO
